#2270: External DB Support
Stirling-Tools/Stirling-PDF pull request #2457
Opened 2024-12-15 13:20 UTC by DarioGii

# Description

Please provide a summary of the changes, including relevant motivation and context.

Closes #(issue_number)

## Checklist

- [ ] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have attached images of the change if it is UI based
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] If my code has heavily changed functionality I have updated relevant docs on [Stirling-PDFs doc repo](https://github.com/Stirling-Tools/Stirling-Tools.github.io/blob/main/docs/)
- [x] My changes generate no new warnings
- [ ] I have read the section [Add New Translation Tags](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/HowToAddNewLanguage.md#add-new-translation-tags) (for new translation tags only)

2024-12-15 13:26 UTC, DarioGii commented on src/main/java/stirling/software/SPDF/SPDFApplication.java
> +    private static String[] getActiveProfile(String[] args) {
Sets the active profile(s). Will be set to `default` if nothing is selected

2024-12-15 13:29 UTC, DarioGii commented on src/main/java/stirling/software/SPDF/config/security/database/DatabaseConfig.java
This class sets the DB configuration

2024-12-15 13:31 UTC, DarioGii commented on src/main/java/stirling/software/SPDF/model/ApplicationProperties.java
> +    @Data
New `Datasource` class

2024-12-15 13:31 UTC, DarioGii commented on src/main/java/stirling/software/SPDF/model/ApplicationProperties.java
> +    public enum Driver {
New `Driver` class

2024-12-15 13:34 UTC, DarioGii commented on src/main/resources/settings.yml.template
> +  datasource:
Configure the DB connection here

2024-12-15 23:28 UTC, Frooodle requested changes

2024-12-15 23:28 UTC, Frooodle commented on src/main/resources/application.properties
> -spring.datasource.url=jdbc:h2:file:./configs/stirling-pdf-DB-2.3.232;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
We should support and still default to using a DB file for ease of adoption and use of users,
We should still allow H2 file connection and ensure this is the default type 
But still offer it to users for postgres etc

2024-12-15 23:28 UTC, Frooodle commented on src/main/resources/settings.yml.template
> +    driver: postgresql
add comment stating the other driver types, example URLs etc

2024-12-15 23:28 UTC, Frooodle commented on src/main/java/stirling/software/SPDF/model/ApplicationProperties.java
> +        private String password;
password needs @ToString.Exclude to avoid logging

2025-01-02 12:27 UTC, Frooodle requested changes

2025-01-02 12:27 UTC, Frooodle commented on src/main/java/stirling/software/SPDF/SPDFApplication.java
> +    private static final Logger logger = LoggerFactory.getLogger(SPDFApplication.class);
Remove logger here to maintain the exissting lombok @Slf4j 
Unless there is a reason for this and the renames?

2025-01-02 12:27 UTC, Frooodle commented on src/main/java/stirling/software/SPDF/config/security/InitialSecuritySetup.java
> +    @Autowired private DatabaseInterface databaseService;
Switch to using the autowired via constructor instead (I think you removed this in a merge?)

2025-01-02 12:27 UTC, Frooodle commented on src/main/java/stirling/software/SPDF/config/security/database/DatabaseService.java
> +    @Autowired
autowired is automatically done here, can be removed

2025-01-02 12:27 UTC, Frooodle commented on src/main/java/stirling/software/SPDF/config/security/database/DatabaseConfig.java
> +        this.runningEE = true; // fixMe: change back
// fixMe: change back

also autowired can be removed here, its auto added by spring

2025-01-02 12:27 UTC, Frooodle commented on src/main/java/stirling/software/SPDF/config/security/database/DatabaseService.java
> +public class DatabaseService implements DatabaseInterface {
I think this class only applies to H2 right? we need checks to skip everything here if its not H2

2025-01-02 12:27 UTC, Frooodle commented on src/main/java/stirling/software/SPDF/config/security/database/DatabaseService.java
> +public class DatabaseService implements DatabaseInterface {
And we need to test 
http://localhost:8080/database
For H2 still works as expected, and expected behaviour is probably to disable  backups for non H2 
Expectation is if its external database that database should handle any backups etc

Imports should be supported in both formats
A user should be able to
h2 -> export
and then import into postgres with that data

2025-01-02 12:27 UTC, Frooodle commented on src/main/resources/settings.yml.template
> +    customDatabaseUrl: jdbc:postgresql://localhost:5432/postgres # set the url for your own custom database connection
add note saying if URL provided then xyz is not needed

2025-01-02 12:40 UTC, DarioGii commented on src/main/java/stirling/software/SPDF/SPDFApplication.java
> +    private static final Logger logger = LoggerFactory.getLogger(SPDFApplication.class);
I think that came in accidentally while rebasing earlier 😅  will remove

2025-01-06 17:38 UTC, DarioGii commented on src/main/java/stirling/software/SPDF/config/security/database/DatabaseService.java
> +public class DatabaseService implements DatabaseInterface {
Will work on this in a new ticket

2025-01-06 17:59 UTC, DarioGii commented
/deployr

2025-01-06 18:15 UTC, DarioGii commented
/deployr

2025-01-06 18:18 UTC, DarioGii commented
/deployr

2025-01-06 18:22 UTC, DarioGii commented
/deploypr

2025-01-06 18:28 UTC, Frooodle requested changes

2025-01-06 18:28 UTC, Frooodle commented on build.gradle
> +        implementation "org.springframework:spring-jdbc"
Add version number here

2025-01-06 18:58 UTC, merged