Corrected the reading of the port. See: #834
Stirling-Tools/Stirling-PDF pull request #855
Opened 2024-02-24 12:11 UTC by Ludy87

# Description

Fix: Overriding Default Server Port

Do not merge this PR until PR #853 is merged.

Closes #834

## Checklist:

- [x] I have read the [Contribution Guidelines](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

## Contributor License Agreement

By submitting this pull request, I acknowledge and agree that my contributions will be included in Stirling-PDF and that they can be relicensed in the future under the MPL 2.0 (Mozilla Public License Version 2.0) license.

(This does not change the general open-source nature of Stirling-PDF, simply moving from one license to another license)

2024-02-24 16:23 UTC, sbplat commented
Has this been tested with docker (default port, custom port, etc.)?

2024-02-24 16:26 UTC, Ludy87 commented
No, not in docker, I wouldn't know how to do that. I only tested it locally with `gradlew bootRun.`

2024-02-24 19:44 UTC, Frooodle approved these changes

2024-02-24 21:36 UTC, Frooodle requested changes

2024-02-24 21:36 UTC, Frooodle commented on src/main/java/stirling/software/SPDF/SPdfApplication.java
> +    @Autowired ApplicationProperties applicationProperties;
whats applicationProperties for?

2024-02-25 08:16 UTC, Ludy87 commented on src/main/java/stirling/software/SPDF/SPdfApplication.java
> +    @Autowired ApplicationProperties applicationProperties;
outdated import, i removed

2024-02-25 16:44 UTC, sbplat approved these changes

2024-02-25 22:25 UTC, Frooodle approved these changes

2024-02-26 00:15 UTC, merged